[package]
name = "ark-ec-vrfs-bandersnatch-example"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ec-vrfs ={ git = "https://github.com/davxy/ark-ec-vrfs", rev = "6b07f6f", features = ["bandersnatch", "ring", "parallel", "test-vectors"] }
hex = "0.4.3"
